import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Heading from "@/components/Heading";

export const metadata = {
  title: "Career | Hey-Stack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div className="bg-[#E4ECFF] ">
        <NavBar />
        <Heading>Careers</Heading>
      </div>
      {children}
      <Footer />
    </>
  );
}
