import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Heading from "@/components/Heading";

export const metadata = {
  title: "Hey-Stack | Terms and Conditions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <div className="bg-gradient-to-b from-[#E4ECFF] via-blue-100 to-white lg:h-[20rem] bg-opacity-20">
        <NavBar />
        <Heading>Terms of Service</Heading>
      </div>
      {children}
      <Footer />
    </>
  );
}
