import { Inter } from "next/font/google";
import "./globals.css";

import { ApolloWrapper } from "@/utils/apollo-wrapper";
import NavBar from "@/components/NavBar";
import MobileNavbar from "@/components/MobileNavBar";
import Top from "@/components/Top";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hey-Stack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <div className="sticky inset-0 z-50 block w-full lg:hidden">
            <MobileNavbar />
          </div>
          {children}
        </ApolloWrapper>
        <Top />
      </body>
    </html>
  );
}
