import { Inter, Poppins } from "next/font/google";
import "./globals.css";

import { ApolloWrapper } from "@/utils/apollo-wrapper";
import MobileNavbar from "@/components/MobileNavBar";
import Top from "@/components/Top";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Hey-Stack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} scroll-smooth`}>
        <ApolloWrapper>
          <div className="sticky inset-0 z-50 block w-full lg:hidden">
            <MobileNavbar />
          </div>
          {children}
        </ApolloWrapper>
        <Top />
      </body>
    </html>
  );
}
