import { Inter, Poppins } from "next/font/google";
import "./globals.css";

import { ApolloWrapper } from "@/utils/apollo-wrapper";
import NavBar from "@/components/NavBar";
import MobileNavbar from "@/components/MobileNavBar";
import { BlogsProvider } from "@/context/BlogContext";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Hey-Stack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ApolloWrapper>
          <div className="sticky inset-0 lg:hidden block  w-full z-50">
            <MobileNavbar />
          </div>
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}
